<a href="https://colab.research.google.com/github/Jagadeesh-krishna/program/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
!pip install numpy

In [6]:
import numpy as np
l=[1, 2, 3, 4, 5]
print(l)
print(type(l))
l=np.array(l)
print(l)
print("type of array", type(l))
print(l.ndim)

[1, 2, 3, 4, 5]
<class 'list'>
[1 2 3 4 5]
type of array <class 'numpy.ndarray'>
1


In [7]:
l1=[1,2,3,4]
l2=[5,6,7,8]
l3=[11,12,13,14]
l4=np.array([l1,l2,l3])
print(l4)
print(l4.ndim)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [11 12 13 14]]
2


In [8]:
l1=[[1,2],[3,4]]
l2=[[5,6],[7,8]]
l3=np.array([l1,l2])
print(l3)
print(l3.ndim)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
3


In [9]:
# different array methods

In [10]:
l=[1,3,4]
p=(1,3,4)
l=np.array(l)
p=np.array(p)
print(l)
print(p)

[1 3 4]
[1 3 4]


In [11]:
# fromiter
l=[1,2,3,4]
arr=np.fromiter(l, dtype=int)
print(arr)

[1 2 3 4]


In [12]:
# arange
l=np.arange(5)
print(l)
l=np.arange(1,9)
print(l)
l=np.arange(1,10,2)
print(l)

[0 1 2 3 4]
[1 2 3 4 5 6 7 8]
[1 3 5 7 9]


In [13]:
# linspace
arr=np.linspace(1,5,8)
print(arr)

[1.         1.57142857 2.14285714 2.71428571 3.28571429 3.85714286
 4.42857143 5.        ]


In [14]:
# empty
arr=np.empty((5,3))
print(arr)

[[3.95926977e-315 0.00000000e+000 5.76405441e-317]
 [6.68740380e-310 6.68740380e-310 6.68740381e-310]
 [5.76405441e-317 6.68740381e-310 5.76405441e-317]
 [6.68740380e-310 5.76405441e-317 6.68740378e-310]
 [5.76405441e-317 6.68740380e-310 6.32404027e-322]]


In [15]:
# zeros
arr=np.zeros((4,4))
print(arr)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [16]:
arr=np.ones((4,4))
print(arr)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [17]:
arr=np.array([[1,2,3],[4,5,6]])
print(arr)
print(arr.shape)
print(arr.size)
print(arr.dtype
      )

[[1 2 3]
 [4 5 6]]
(2, 3)
6
int64


In [18]:
a=np.array([[1,2,3],[1,2,3]])
print(a)
print(a.sum(axis=0))


[[1 2 3]
 [1 2 3]]
[2 4 6]


In [19]:
# indexing
l=[1,2,3,4,5]
a=np.array(l)
print(a[:2])
print(a[-1])

[1 2]
5


In [20]:
# 2d indexing
l2=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(l2)
print(l2[0,0])
print(l2[2,2])
print(l2[0])
print(l2[:,0])
print(l2[:,2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
1
9
[1 2 3]
[1 4 7]
[3 6 9]


In [21]:
# slicing
l=[1,2,3,4,5]
a=np.array(l)
print(a)
print(a[0::2])

[1 2 3 4 5]
[1 3 5]


In [22]:
l=np.array([[1,2,3,4],[4,5,6,7],[8,9,10,11]])
print(l)
print(l[0:2, 0:2])



[[ 1  2  3  4]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[1 2]
 [4 5]]


In [23]:
# reshaping
l=[1,2,3,4,5,6]
l=np.array(l)
print(l)
print(l.ndim)
new_arr=l.reshape(2,3)
print(new_arr)
print(new_arr.ndim)

[1 2 3 4 5 6]
1
[[1 2 3]
 [4 5 6]]
2


In [24]:
# resize

l=np.array([1,2,3,4,5])
l.resize(2,3)
print(l)


[[1 2 3]
 [4 5 0]]


In [25]:
# broadcasting
l=np.array([1,2,3,4,5])
print(l*2)

[ 2  4  6  8 10]


In [26]:
import numpy as np

In [27]:
arr1= np.array([1,2,3])
arr2= np.array([10,20,30])
print(arr1+arr2)
print(arr1-arr2)
print(arr1*arr2)
print(arr1/arr2)
print(arr1//arr2)
print(arr1%arr2)
print(arr1**arr2)

[11 22 33]
[ -9 -18 -27]
[10 40 90]
[0.1 0.1 0.1]
[0 0 0]
[1 2 3]
[              1         1048576 205891132094649]


In [28]:
# Aggregate functions: functions used to summarize the data
l=np.array([10,20,30,40,50,60])
# add all the elements=sum
print(np.sum(l))
# average
print(np.mean(l))
# minimum
print(np.min(l))
# maximum
print(np.max(l))
# standard deviation
print(np.std(l))
# variance
print(np.var(l))
# size of elements in an array
print(np.size(l))
# argmax: gives the index position of the largest value
print(np.argmax(l))
# argmax: gives the index position of the smallest value
print(np.argmin(l))
# applying square root
print(np.sqrt(l))


210
35.0
10
60
17.07825127659933
291.6666666666667
6
5
0
[3.16227766 4.47213595 5.47722558 6.32455532 7.07106781 7.74596669]


In [31]:
# absolute function to convert negative to positive
arr=np.array([-1,-2,-3,-4,-5])
print(np.abs(arr))

[1 2 3 4 5]


In [33]:
# numpy rounding functions: round values to nearest integer
arr=np.array([1.2,2.7,3.5,11.8])
print(np.round(arr))

[ 1.  3.  4. 12.]


In [35]:
arr=np.array([1.2,2.7,3.5,11.8])
# floor: it will always give lower integer value
# 2.7 = 2
print(np.floor(arr))

[ 1.  2.  3. 11.]


In [36]:
# ceil: it always gives upper integer values
arr=np.array([1.2,2.7,3.5,11.8])
# 1.2 = 2
# 3.3 = 4
print(np.ceil(arr))

[ 2.  3.  4. 12.]
