<a href="https://colab.research.google.com/github/Jagadeesh-krishna/program/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install numpy

In [ ]:
import numpy as np
l=[1, 2, 3, 4, 5]
print(l)
print(type(l))
l=np.array(l)
print(l)
print("type of array", type(l))
print(l.ndim)

[1, 2, 3, 4, 5]
<class 'list'>
[1 2 3 4 5]
type of array <class 'numpy.ndarray'>
1


In [ ]:
l1=[1,2,3,4]
l2=[5,6,7,8]
l3=[11,12,13,14]
l4=np.array([l1,l2,l3])
print(l4)
print(l4.ndim)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [11 12 13 14]]
2


In [ ]:
l1=[[1,2],[3,4]]
l2=[[5,6],[7,8]]
l3=np.array([l1,l2])
print(l3)
print(l3.ndim)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
3


In [ ]:
# different array methods

In [ ]:
l=[1,3,4]
p=(1,3,4)
l=np.array(l)
p=np.array(p)
print(l)
print(p)

[1 3 4]
[1 3 4]


In [ ]:
# fromiter
l=[1,2,3,4]
arr=np.fromiter(l, dtype=int)
print(arr)

[1 2 3 4]


In [ ]:
# arange
l=np.arange(5)
print(l)
l=np.arange(1,9)
print(l)
l=np.arange(1,10,2)
print(l)

[0 1 2 3 4]
[1 2 3 4 5 6 7 8]
[1 3 5 7 9]


In [ ]:
# linspace
arr=np.linspace(1,5,8)
print(arr)

[1.         1.57142857 2.14285714 2.71428571 3.28571429 3.85714286
 4.42857143 5.        ]


In [ ]:
# empty
arr=np.empty((5,3))
print(arr)

[[3.54733790e-315 0.00000000e+000 6.66351300e-310]
 [6.66351299e-310 5.76405441e-317 6.66351299e-310]
 [6.66351298e-310 6.66351298e-310 6.66351299e-310]
 [5.76405441e-317 6.66351298e-310 6.66351298e-310]
 [6.66351299e-310 5.76405441e-317 6.32404027e-322]]


In [ ]:
# zeros
arr=np.zeros((4,4))
print(arr)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
arr=np.ones((4,4))
print(arr)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
arr=np.array([[1,2,3],[4,5,6]])
print(arr)
print(arr.shape)
print(arr.size)
print(arr.dtype
      )

[[1 2 3]
 [4 5 6]]
(2, 3)
6
int64


In [ ]:
a=np.array([[1,2,3],[1,2,3]])
print(a)
print(a.sum(axis=0))


[[1 2 3]
 [1 2 3]]
[2 4 6]


In [ ]:
# indexing
l=[1,2,3,4,5]
a=np.array(l)
print(a[:2])
print(a[-1])

[1 2]
5


In [ ]:
# 2d indexing
l2=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(l2)
print(l2[0,0])
print(l2[2,2])
print(l2[0])
print(l2[:,0])
print(l2[:,2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
1
9
[1 2 3]
[1 4 7]
[3 6 9]


In [ ]:
# slicing
l=[1,2,3,4,5]
a=np.array(l)
print(a)
print(a[0::2])

[1 2 3 4 5]
[1 3 5]


In [ ]:
l=np.array([[1,2,3,4],[4,5,6,7],[8,9,10,11]])
print(l)
print(l[0:2, 0:2])



[[ 1  2  3  4]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[1 2]
 [4 5]]


In [ ]:
# reshaping
l=[1,2,3,4,5,6]
l=np.array(l)
print(l)
print(l.ndim)
new_arr=l.reshape(2,3)
print(new_arr)
print(new_arr.ndim)

[1 2 3 4 5 6]
1
[[1 2 3]
 [4 5 6]]
2


In [ ]:
# resize

l=np.array([1,2,3,4,5])
l.resize(2,3)
print(l)


[[1 2 3]
 [4 5 0]]


In [ ]:
# broadcasting
l=np.array([1,2,3,4,5])
print(l*2)

[ 2  4  6  8 10]
